### ISSUE TITLE
Improve Navbar design

### ISSUE THREAD

**Issue by YugalPradhan** [YugalPradhan/Lovecare#1]
Navbar doesn,t look good when using in mobile and design is quite simple, help to improve design of navbar.

**Comment by amitroy-thedev** [comment]
Hey @YugalPradhan assign me this project..

**Comment by VidishaAG** [comment]
Can I be assigned please? I want to work on this

**Comment by manishgupta416** [comment]
I want to fix this issue, can you assign me this issue

**Comment by gcsandesh** [comment]
Whoever is going to work on this issue, do fix the fonts in navbar links too.

**Comment by YugalPradhan** [comment]
@manishgupta416  go ahead

**Comment by manishgupta416** [comment]
can you please review my pr

**Comment by srini-vasan-c** [comment]
If issue still open, could you pls assign to me. I am interested to contribute

**Comment by kanikarajpal** [comment]
Can you please assign this to me?

**Comment by nidhish-srivastava** [comment]
I will make the Navbar more attractive ,make it sticky and add a lil animation,also make it responsive by adding a hamburger
Can u asign the issue to me @YugalPradhan

**Comment by YugalPradhan** [comment]
@nidhish-srivastava go with it
