### ISSUE TITLE
Enhancement of Donate Form

### ISSUE THREAD

**Issue by gcsandesh** [YugalPradhan/Lovecare#2]
The UI of Donate Form can be enhanced by:
- changing the fonts used
- modifying the shape of buttons
- adding space between the radio buttons and corresponding texts.
- modifying placeholder texts and adding indentation
- changing the default outline when form element is active
- the hover effect on "Donate Now" button is also bad for UX.

Assign it to me, I would like to work on this.

**Comment by YugalPradhan** [comment]
@SandeshGC  go ahead

**Comment by gcsandesh** [comment]
Hey @YugalPradhan I think you need to add hacktoberfest label to the issue and the PR too.
