### ISSUE TITLE
Add transition in "Donate Now" button and padding in Placeholder of Donate form.

### ISSUE THREAD

**Issue by hackbysarthak03** [YugalPradhan/Lovecare#4]
Background can be made full screen and can be fixed. This will increase the UI Experience of the Website.

**Comment by YugalPradhan** [comment]
@hackbysarthak03  Do you wanna contribute code

**Comment by gcsandesh** [comment]
This will be solved in issue #2

**Comment by hackbysarthak03** [comment]
Yes I can contribute on this.

**Comment by hackbysarthak03** [comment]
Please Assign this task to me @YugalPradhan

**Comment by YugalPradhan** [comment]
@hackbysarthak03  go for it
